### ISSUE TITLE
Can't get Canu corrections to run 'Error occurred during initialization of VM'

### ISSUE THREAD

**Issue by efogarty11** [marbl/canu#1016]
Hello! I'm using Canu for the first time to assemble Nanopore reads but I'm getting stuck on the corrections part (the way I'm running it I'm doing corrections, trimming and assembly separately). 

We've been running it on a grid and we use Canu 1.7.1. 

This was the command I ran:
```bash
module load canu

export _JAVA_OPTIONS="-Xmx400g"

canu -correct \
     -p isolate_214_Canu_assembly \
     -d /pass/barcodes_1to8/barcode01/canu_assembly \
     genomeSize=2.7k \
     maxThreads=20 \
     -nanopore-raw /pass/barcodes_1to8/barcode01/barcodes_merged/barcode01_merged \
     gridEngineMemoryOption="-l h_vmem=MEMORY" \
     gridEngineThreadsOption="-pe make THREADS" \
     oeaMemory=64 \
     corOvlMemory=64 \
     cormhapMemory=2000
```
and this is the error it gave me. 
<img width="489" alt="screenshot 2018-07-20 12 10 00" src="https://user-images.githubusercontent.com/38365171/43015755-eecaa754-8c15-11e8-9922-c77ee689b31e.png">

When I got a similar error, I had been using `cormhapMemory=700` and the error told me it could not reserve enough space for the 791GB object heap. I increased it to 1000 and it told me it could not reserve enough space for the 1097GB object heap. It seems like everytime I increase the cormhapMemory it increases what is required.

Someone else in my lab successfully ran it with:
```bash
export _JAVA_OPTIONS="-Xmx400g"

canu -correct \
     -p COP_ALL \
     -d 02_CORRECTED/COP_ALL \
     genomeSize=3.3m \
     maxThreads=20 \
     -nanopore-raw 01_FASTQ/coprococcus_comes_passed.fastq.gz 01_FASTQ/coprococcus_comes_failed.fastq.gz \
     gridEngineMemoryOption="-l h_vmem=MEMORY" \
     gridEngineThreadsOption="-pe make THREADS" \
     oeaMemory=64 \
     corOvlMemory=64 \
     cormhapMemory=600
```

Thank you so much in advance!

**Comment by skoren** [comment]
Fundamentally, the error is in the interaction of your grid and the JVM, it can't allocate the 2tb of memory you told Canu to use. However, it should not be necessary to set memory for the steps explicitly. The memory you're setting with JAVA_OPTIONS is also inconsistent with what you're telling Canu to use so do not set it. 

I would guess your grid engine memory and threads options are not correct. Typically pe make is assigned round_robin which means all the compute is not on a single node. The h_vmem resource is also typically not a consumable. As a result you aren't actually reserving the proper resources for the run. Can you run
```
qconf -spl
qconf -sp make
qconf -sc
```
and post the outputs?

Given your small genome size, you can also just run on a single node and not have to worry about the cluster configuration. Just add useGrid=false and do not set _JAVA_OPTIONS or other memory options for Canu.

**Comment by efogarty11** [comment]
I tried adding useGrid=false and that worked! Or it's working so far anyway. Thank you so much!

**Comment by skoren** [comment]
That will run it on a single node so make sure you don't launch it on the head node but one of your compute nodes. You may also want to add ```-fast```.

Re-open if it fails with useGrid=false or you want to figure out the resource request options for your grid.

**Comment by MFSeidl** [comment]
Hello, I am experiencing the same issue with Canu on our HPC with SGE. 
I am using a different pe that is not set to round_robin but to pe_slots. I would be curious about the resource request options to make sure that Canu via SGE and JVM communicate well
Thx
Michael

**Comment by skoren** [comment]
It's unlikely your issue is related to this since the issue here was explicitly requesting large memory sizes for the JVM. 

You should make sure the memory resource is consumable and is actually being reserved on the node. Check what the canu command uses for the JVM and what it requested from the grid. In some cases, there are JVM configuration issues where the default GC and threading option increases memory usage (see #298for a disussion), in that case you want to over-request memory (something like ```mhapMemory=48
gridOptionsCorMhap="-l h_vmem=4g -pe sharedmem 16"```) would try to use 48gb but reserve 64 on the cluster.

**Comment by MFSeidl** [comment]
Thanks for the reply. I think this is indeed what is happening (increasing the memory usage). I will try with the settings you suggested. 

In general I suspect that there might be some issues with the configuration on the HPC. I just downloaded the latest Canu version from git and it complains directly at start that the environment I requested (its not 'make', according to the system admin) didn't set 'job_is_first_task'. This environment uses $pe_slots rather than $round_robin

**Comment by MFSeidl** [comment]
I run with your suggested settings (changed the pe to the one we have) but it fails again

Found java:
   /home/uu_tbb/mseidl/software/jre1.8.0_211/bin/java
   Error occurred during initialization of VM

and 

Error occurred during initialization of VM
Could not reserve enough space for 45299712KB object heap

precompute.sh requested
java -d64 -XX:ParallelGCThreads=12 -server -Xms44237m -Xmx44237m

**Comment by skoren** [comment]
I think your memory reservation isn't working. What was the canu grid request for this job (in ```correction/1-overlapper/*.jobSubmit*sh```)? Check your grid memory options for a consumable resources and post the results here (```qconf -sc|grep MEMORY```), you want something like this:
```
#name               shortcut   type        relop requestable consumable default  urgency 
#----------------------------------------------------------------------------------------
mem_free            mf         MEMORY      <=    YES         YES        0        0
```

**Comment by MFSeidl** [comment]
okay, the request: 

qsub \
  -l h_vmem=3413m -pe threaded 12 -l h_rt=24:00:00 -l h_vmem=4g -pe threaded 16 -j y -o precompute.\$TASK_ID.out \
  -cwd -N "cormhap_Vlong" \
  -t 1-3 \
  ./precompute.sh 0 \
> ./precompute.jobSubmit-01.out 2>&1

This is the output of qconf:

h_core              h_core     MEMORY    <=    YES         NO         0         0
h_data              h_data     MEMORY    <=    YES         NO         0         0
h_fsize             h_fsize    MEMORY    <=    YES         NO         0         0
h_rss               h_rss      MEMORY    <=    YES         NO         0         0
h_stack             h_stack    MEMORY    <=    YES         NO         0         0
h_vmem              h_vmem     MEMORY    <=    YES         JOB        10G       0
mem_free            mf         MEMORY    <=    YES         NO         0         0
mem_total           mt         MEMORY    <=    YES         NO         0         0
mem_used            mu         MEMORY    >=    YES         NO         0         0
s_core              s_core     MEMORY    <=    YES         NO         0         0
s_data              s_data     MEMORY    <=    YES         NO         0         0
s_fsize             s_fsize    MEMORY    <=    YES         NO         0         0
s_rss               s_rss      MEMORY    <=    YES         NO         0         0
s_stack             s_stack    MEMORY    <=    YES         NO         0         0
s_vmem              s_vmem     MEMORY    <=    YES         NO         0         0
swap_free           sf         MEMORY    <=    YES         NO         0         0
swap_rate           sr         MEMORY    >=    YES         NO         0         0
swap_rsvd           srsv       MEMORY    >=    YES         NO         0         0
swap_total          st         MEMORY    <=    YES         NO         0         0
swap_used           su         MEMORY    >=    YES         NO         0         0
tmpspace            ts         MEMORY    <=    YES         JOB        1G        0
virtual_free        vf         MEMORY    <=    YES         NO         0         0
virtual_total       vt         MEMORY    <=    YES         NO         0         0
virtual_used        vu         MEMORY    >=    YES         NO         0         0

**Comment by skoren** [comment]
Ah, the issue is the memory is set to consumable as JOB which means it's only requesting 4gb not 4*16 as Canu expects. This was fixed post the 1.8 release which I assume you're using? If so, your best option is to update to the latest from the repo and build it yourself (see readme for instructions). Then, Canu should auto-detect the JOB setting and request memory per job not per core. Otherwise, you'd have to over-request memory for all your jobs, something like ```maxMemory=64 gridOptions="-l h_vmem=64g"```.

**Comment by MFSeidl** [comment]
Thanks - I also got the most recent version from git and compiled (Canu snapshot v1.8 +268 changes). This recognises the SGE environment, but immediately indicates that there is an issue with the pe:
```-- User supplied Parallel Environment 'threaded'.
-- User supplied Memory Resource      'h_rt=24:00:00 -l h_vmem'.

ERROR:  Sun Grid Engine parallel environment 'threaded' didn't set 'job_is_first_task'.
ERROR:
ERROR:    pe_name            threaded
ERROR:    slots              6000
ERROR:    user_lists         NONE
ERROR:    xuser_lists        NONE
ERROR:    start_proc_args    NONE
ERROR:    stop_proc_args     NONE
ERROR:    allocation_rule    $pe_slots
ERROR:    control_slaves     FALSE
ERROR:    job_is_first_task  FALSE
ERROR:    urgency_slots      min
ERROR:    accounting_summary FALSE
ERROR:    qsort_args         NONE

ABORT:
ABORT: Canu snapshot v1.8 +268 changes (r9478 b00a9c2f8c17b2273f1123eed3013a50252dc5b8)
ABORT: Don't panic, but a mostly harmless error occurred and Canu stopped.
ABORT: Try restarting.  If that doesn't work, ask for help.
ABORT:
ABORT:   can't configure for SGE.
ABORT:
```

**Comment by skoren** [comment]
Yeah it is correct to complain since that doesn't match the expectation. You can still specify the user-supplied thread parameter (gridEngineThreadsOption="-pe threaded", don't supply the memory option.

**Comment by MFSeidl** [comment]
okay, but do I understand correctly that I first need to get the issue with the `job_is_first_task` sorted out? Bc even with the options `gridEngineResourceOption="-pe threaded THREADS -l h_vmem=MEMORY"` I still get the error...

**Comment by skoren** [comment]
Yes, if possible it would be good to have the correct pe job option available. This is a recent check added post 1.8 as well. If your cluster admins don't want to change it, you can work around it by editing the code in ```src/pipelines/canu/Grid_SGE.pm``` and change line 246 from:
```
246                 $jf = 1   if (m/job_is_first_task.*TRUE/);     #  The fisrt task (slot) does actual work.
```
to 
```
246                 $jf = 1;
```
