### ISSUE TITLE
Error metagenome read correction

### ISSUE THREAD

**Issue by Raymi1** [marbl/canu#1370]
Hello, I attempted to run canu with a metagenome. I used the following command : `canu -p metagenomeAssembly -d assembly genomeSize=5m corOutCoverage=10000 corMhapSensitivity=high corMinCoverage=0 redMemory=32 oeaMemory=32 batMemory=200 gridEngineThreadsOption='--cpus-per-task THREADS' maxMemory=230G maxThreads=8 -nanopore-raw file.fasta.gz`

However I get the following error message : `ABORT: Canu snapshot v1.8 +166 changes (r9376 9f15c0d1e6e2ca40d718c70f8da1c716189757e5)
ABORT: Don't panic, but a mostly harmless error occurred and Canu stopped.
ABORT: Try restarting.  If that doesn't work, ask for help.
`
It seems to come from read correction jobs that failed. 

When I look in the following file : `correction/2-correction/results/0001.err` , I can see : `falconsense: utility/edlib.C:400: void edlibAlignmentToStrings(const unsigned char*, int, int, int, int, int, const char*, const char*, char*, char*): Assertion `strlen(qry_aln_str) == alignmentLength && strlen(tgt_aln_str) == alignmentLength' failed`

Please, can you help me

**Comment by skoren** [comment]
This is typically caused by non-ACGT characters in the input reads. Have you checked for bad data in the input fastq? This should have been fixed in 1.8 though so it would be good if you can share this data to reproduce locally.

**Comment by skoren** [comment]
Did you ever get an assembly, are you able to share the input reads for debugging?

**Comment by Raymi1** [comment]
Sorry for the this late answer. The input reads contained effectively non-ACTG characters. I corrected by removing some reads from the input data. And it has worked. 
I can't share my input reads because I don't have them anymore. I'll try to retrive them.

Thanks

**Comment by skoren** [comment]
I was able to reproduce a crash by adding non-ACGT characters in your version of Canu and got the same error. This bug was re-introduced after 1.8 and I confirmed the release works OK. So you could also run the 1.8 release if you want to not have to pre-screen your data for ACGT. 

I also confirmed this is still an issue in the latest tip but due to a different code change (your bug was fixed and a different one introduced).

**Comment by skoren** [comment]
This should now be fixed in the 1.9 branch
