### ISSUE TITLE
issues downloading canu 1.3

### ISSUE THREAD

**Issue by EpiBlake** [marbl/canu#157]
I am getting an error when I attempt to download the new 1.3 release, both when I attempt to download the binary and when I attempt to compile from source. 

Downloading from binary:
I get the following error indicating something may be wrong with the built binary. 
```
dyld: lazy symbol binding failed: Symbol not found: _Perl_xs_handshake
  Referenced from: /Users/user/Documents/ComputerStuff/Programs/canu-1.3/Darwin-amd64/bin/lib/canu/lib/perl5/darwin-thread-multi-2level/auto/Filesys/Df/Df.bundle
  Expected in: flat namespace

dyld: Symbol not found: _Perl_xs_handshake
  Referenced from: /Users/user/Documents/ComputerStuff/Programs/canu-1.3/Darwin-amd64/bin/lib/canu/lib/perl5/darwin-thread-multi-2level/auto/Filesys/Df/Df.bundle
  Expected in: flat namespace

Trace/BPT trap: 5
```

Compiling from source:
I get an error that omp.h is missing, and I cannot find it anywhere in the code repo. 
```
falcon_sense/falcon_sense.C:33:10: fatal error: 'omp.h' file not found
#include <omp.h>
         ^
1 error generated.
make: *** [/Users/bhanson/Downloads/canu-1.3/Darwin-amd64/obj/falcon_sense/falcon_sense/falcon_sense.o] Error 1
make: *** Waiting for unfinished jobs....
5 warnings generated.
overlapBasedTrimming/trimReads-largestCovered.C:39:29: warning: unused parameter 'ibgn' [-Wunused-parameter]
               uint32       ibgn,
                            ^
overlapBasedTrimming/trimReads-largestCovered.C:40:29: warning: unused parameter 'iend' [-Wunused-parameter]
               uint32       send,
                            ^
overlapBasedTrimming/trimReads-largestCovered.C:47:29: warning: unused parameter 'minReadLength' [-Wunused-parameter]
               uint32       minReadLength) {
                            ^
3 warnings generated.
```

When I went to download canu 1.2 from the binary, it installed right away without any problems which makes me think this issue is localized to the 1.3 build.

**Comment by skoren** [comment]
Your first issue is a perl version incompatibility, probably due to a different perl or OS X version from the build. If you install the Df module on your system, the binaries should fix it. I made a test build using an older perl version (ftp://ftp.cbcb.umd.edu/pub/data/sergek/canu-1.3.Darwin-amd64.tar.bz2), see if it resolves your issue.

The second error is missing OpenMP from your compiler.It looks like this file has a bug and is missing the check for a missing OpenMP. I'd recommend compiling with a macports or otherwise installed gcc rather than clang since you'd lose almost all parallel code in the assembler without OpenMP.

**Comment by EpiBlake** [comment]
Ok, I was able to get the perl version incompatibility to resolve by updating my perl version. Now that i have it installed, I am getting a gatekeeper error when trying to run the toy example from your Quick Start. 

I am running: 
`canu-1.3/Darwin-amd64/bin/canu -p ecoli -d ecoli-auto genomeSize=4.8m maxThreads=2 -pacbio-raw p6.25x.fastq`

And I am getting the following error: 

```
-- Starting command on Mon Jun 13 15:06:01 2016 with 147 GB free disk space

    /Users/bhanson/Downloads/canu-1.3/Darwin-amd64/bin/gatekeeperCreate \
      -minlength 1000 \
      -o /Users/bhanson/Downloads/ecoli-auto/correction/ecoli.gkpStore.BUILDING \
      /Users/bhanson/Downloads/ecoli-auto/correction/ecoli.gkpStore.gkp \
    > /Users/bhanson/Downloads/ecoli-auto/correction/ecoli.gkpStore.BUILDING.err 2>&1
sh: line 4:  8783 Trace/BPT trap: 5       /Users/bhanson/Downloads/canu-1.3/Darwin-amd64/bin/gatekeeperCreate -minlength 1000 -o /Users/bhanson/Downloads/ecoli-auto/correction/ecoli.gkpStore.BUILDING /Users/bhanson/Downloads/ecoli-auto/correction/ecoli.gkpStore.gkp > /Users/bhanson/Downloads/ecoli-auto/correction/ecoli.gkpStore.BUILDING.err 2>&1

-- Finished on Mon Jun 13 15:06:02 2016 (1 second) with 147 GB free disk space
----------------------------------------
ERROR:
ERROR:  Failed with exit code 133.  (rc=34048)
ERROR:
================================================================================
Don't panic, but a mostly harmless error occurred and canu failed.

canu failed with 'gatekeeper store exists, but contains no reads'.
```

**Comment by skoren** [comment]
That looks like an OS X version issue (it can't load some dynamic library) so I think for your system, you'l have to build the release locally. I would recommend installing a recent GCC and building from the release.

**Comment by EpiBlake** [comment]
I have checked on gcc and I have the most recent version. I am still getting the fatal error: 'omp.h' file not found message. 

No worries though, I'm giving up on the OS X version for now. I was able to get 1.3 up and running on a linux build we have here. 

Thanks for your help!

**Comment by skoren** [comment]
If you have an omp.h error, you're either using clang (which can be named gcc on OS X)
```
which gcc
gcc --version
$ which gcc
/usr/bin/gcc
$ gcc --version
Configured with: --prefix=/Library/Developer/CommandLineTools/usr --with-gxx-include-dir=/usr/include/c++/4.2.1
Apple LLVM version 7.0.2 (clang-700.1.81)
Target: x86_64-apple-darwin14.5.0
Thread model: posix
```

Which is clang, the default compiler in OS X which does not support OpenMP, you need any GCC which supports OpenMP to avoid the omp.h error. You can install it through home-brew or MacPorts.
