### ISSUE TITLE
ABORT:   failed to partition reads for correction.

### ISSUE THREAD

**Issue by Hollowed-Mind** [marbl/canu#2234]
I can run the canu program successfully using two different fastqs of 20x reads from 5,160,000 base pairs, but the second I try running it with reads from smaller sequences it fails in the correction step.

I've tried it with 20x coverage reads from 10,000bp, 8000bp and ~4000bp. All fail in the same step. 

Attached are two records from my terminal. One where canu finished the program (from one of two fastq reads from a 5,160,000 bp sample) and one record where canu stalled and aborted (when I tried to use it to assemble reads from a 10,000bp sequence). 

What do you think is going on here? 

[failed_canu_run_record.txt](https://github.com/marbl/canu/files/11887538/failed_canu_run_record.txt)
[successful_canu_run_record.txt](https://github.com/marbl/canu/files/11887539/successful_canu_run_record.txt)

**Comment by skoren** [comment]
I'm not sure I understand what you're trying to do with the downsampling. You're keeping only reads shorter than some threshold for the same dataset as the successful run? If so, 10kb input that failed has only 27 reads and is less than 1x of coverage of the 5mb genome so I think the issue is no reads are left to correct. If the sets w/8 and 4kb thresholds have even fewer reads to correct, then they would be failing for the same reason.

**Comment by Hollowed-Mind** [comment]
> I'm not sure I understand what you're trying to do with the downsampling. You're keeping only reads shorter than some threshold for the same dataset as the successful run? If so, 10kb input that failed has only 27 reads and is less than 1x of coverage of the 5mb genome so I think the issue is no reads are left to correct. If the sets w/8 and 4kb thresholds have even fewer reads to correct, then they would be failing for the same reason.

No, skoren, they are different datasets and come from different ecc_dnas. The issue is the program runs fine when I try it on a large number of reads from a large dna molecule, but when I try it with reads from a smaller molecule it fails.

**Comment by skoren** [comment]
Ah, are you able to share one of the failed sets, like the 10kb one?

**Comment by Hollowed-Mind** [comment]
fa

> Ah, are you able to share one of the failed sets, like the 10kb one?

You mean the actual reads? Sure. github won't let me upload the actual .fastq, but the attached .txt has the same text exactly, just copied over. If you are looking for a log of a failed canu run, see the failed_canu_run_record.txt from my original post.

[10000bp_run.txt](https://github.com/marbl/canu/files/11899842/10000bp_run.txt)

**Comment by brianwalenz** [comment]
Thanks, I just independently reproduced a crash, and also reproduced it with your reads.

**Comment by brianwalenz** [comment]
Fixed!  A nice simple embarrassing bug.

**Comment by Hollowed-Mind** [comment]
https://github.com/marbl/canu/issues/2234#issuecomment-1612105776 So the software change fixes it?

**Comment by brianwalenz** [comment]
Yup!

**Comment by Hollowed-Mind** [comment]
> Yup!

Cool, I'll test it out once my computer finishes its current really long process. Thanks!

**Comment by Hollowed-Mind** [comment]
> Yup!

Sadly, your fix does not resolve the issue. Any attempt to run the reads from the 10000bp fails. Unless you changed more than that one file?

In fact, it seems to produce a new error as now the error log looks different. 

See the errors reported below:
[new_canu_error.txt](https://github.com/marbl/canu/files/11910660/new_canu_error.txt)

**Comment by brianwalenz** [comment]
It is showing the same version string as the buggy version:
```
ABORT: canu snapshot v2.3-development +95 changes (r10366 bf659b146261305f1785b9be03c609063354265b)
```
can you verify it was recompiled, and/or check that `falconsense --version` reports
```
canu snapshot v2.3-development +105 changes (r10376 5453c3fddb944f8d9e3fbc2edd2f1d545a83c949)
```

**Comment by Hollowed-Mind** [comment]
How can I force it to recompile? Sorry, I am new to linux and to this level of programming in general.

Thanks for your help!
________________________________

**Comment by Hollowed-Mind** [comment]
I've tried reinstalling canu from scratch in hopes that the updated code will work better. But each time I do, the make portion of the installation terminates with "make: *** No rule to make target 'bin/canu', needed by '/home/jld170130/CANU/canu/build/bin/canu'.  Stop."

The full readout from my terminal is attached.
________________________________

**Comment by skoren** [comment]
The attachments don't come through email replies to GitHub unfortunately. However, there were some updates to canu's build system recently that likely were the cause of your issues. Try to build it again if you can or you can wait for the next release which should be available later this month.

**Comment by skoren** [comment]
Idle, should have been fixed by the commit and make file updates.
