### ISSUE TITLE
canu failed with 'failed to compute mhap overlaps. How to fix?

### ISSUE THREAD

**Issue by qslin** [marbl/canu#417]
Here is the error log:
```
-- Detected Java(TM) Runtime Environment '1.8.0_45' (from '/common/opt/jdk1.8.0_45/bin/java').
-- Detected gnuplot version '4.2 patchlevel 6 ' (from 'gnuplot') and image format 'png'.
 -- Detected 8 CPUs and 31 gigabytes of memory.
-- Detected Sun Grid Engine in '/opt/gridengine/default'.
-- Grid engine disabled per useGrid=false option.
--
-- Allowed to run   1 job  concurrently, and use up to   8 compute threads and   31 GB memory for stage 'bogart (unitigger)'.
-- Allowed to run   1 job  concurrently, and use up to   8 compute threads and   13 GB memory for stage 'mhap (overlapper)'.
-- Allowed to run   1 job  concurrently, and use up to   8 compute threads and   13 GB memory for stage 'mhap (overlapper)'.
-- Allowed to run   1 job  concurrently, and use up to   8 compute threads and   13 GB memory for stage 'mhap (overlapper)'.
-- Allowed to run   2 jobs concurrently, and use up to   4 compute threads and    6 GB memory for stage 'read error detection (overlap error adjustment)'.
-- Allowed to run   8 jobs concurrently, and use up to   1 compute thread  and    2 GB memory for stage 'overlap error adjustment'.
-- Allowed to run   1 job  concurrently, and use up to   8 compute threads and   31 GB memory for stage 'utgcns (consensus)'.
-- Allowed to run   8 jobs concurrently, and use up to   1 compute thread  and    3 GB memory for stage 'overlap store parallel bucketizer'.
-- Allowed to run   8 jobs concurrently, and use up to   1 compute thread  and   16 GB memory for stage 'overlap store parallel sorting'.
-- Allowed to run   8 jobs concurrently, and use up to   1 compute thread  and    3 GB memory for stage 'overlapper'.
-- Allowed to run   1 job  concurrently, and use up to   8 compute threads and    8 GB memory for stage 'overlapper'.
-- Allowed to run   1 job  concurrently, and use up to   8 compute threads and    8 GB memory for stage 'overlapper'.
-- Allowed to run   1 job  concurrently, and use up to   8 compute threads and   31 GB memory for stage 'meryl (k-mer counting)'.
-- Allowed to run   2 jobs concurrently, and use up to   4 compute threads and   15 GB memory for stage 'falcon_sense (read correction)'.
-- Allowed to run   1 job  concurrently, and use up to   8 compute threads and   13 GB memory for stage 'minimap (overlapper)'.
-- Allowed to run   1 job  concurrently, and use up to   8 compute threads and   13 GB memory for stage 'minimap (overlapper)'.
-- Allowed to run   1 job  concurrently, and use up to   8 compute threads and   13 GB memory for stage 'minimap (overlapper)'.
--
-- This is canu parallel iteration #1, out of a maximum of 2 attempts.
--
-- Final error rates before starting pipeline:
--   
--   genomeSize          -- 420000000
--   errorRate           -- 0.035
--   
--   corOvlErrorRate     -- 0.105
--   obtOvlErrorRate     -- 0.105
--   utgOvlErrorRate     -- 0.105
--   
--   obtErrorRate        -- 0.105
--   
--   cnsErrorRate        -- 0.105
--
--
-- BEGIN CORRECTION
--
-- mhap attempt 1 begins with 40 finished, and 33 to compute.
----------------------------------------
-- Starting concurrent execution on Tue Mar 21 19:56:21 2017 with 62580.688 GB free disk space (33 processes; 1 concurrently)

    /tempdata3/linqs/Mimulus/canu/data_t8/correction/1-overlapper/mhap.sh 32 > /tempdata3/linqs/Mimulus/canu/data_t8/correction/1-overlapper/mhap.000032.out 2>&1
    /tempdata3/linqs/Mimulus/canu/data_t8/correction/1-overlapper/mhap.sh 33 > /tempdata3/linqs/Mimulus/canu/data_t8/correction/1-overlapper/mhap.000033.out 2>&1
    /tempdata3/linqs/Mimulus/canu/data_t8/correction/1-overlapper/mhap.sh 34 > /tempdata3/linqs/Mimulus/canu/data_t8/correction/1-overlapper/mhap.000034.out 2>&1
    /tempdata3/linqs/Mimulus/canu/data_t8/correction/1-overlapper/mhap.sh 36 > /tempdata3/linqs/Mimulus/canu/data_t8/correction/1-overlapper/mhap.000036.out 2>&1
    /tempdata3/linqs/Mimulus/canu/data_t8/correction/1-overlapper/mhap.sh 37 > /tempdata3/linqs/Mimulus/canu/data_t8/correction/1-overlapper/mhap.000037.out 2>&1
    /tempdata3/linqs/Mimulus/canu/data_t8/correction/1-overlapper/mhap.sh 38 > /tempdata3/linqs/Mimulus/canu/data_t8/correction/1-overlapper/mhap.000038.out 2>&1
    /tempdata3/linqs/Mimulus/canu/data_t8/correction/1-overlapper/mhap.sh 39 > /tempdata3/linqs/Mimulus/canu/data_t8/correction/1-overlapper/mhap.000039.out 2>&1
    /tempdata3/linqs/Mimulus/canu/data_t8/correction/1-overlapper/mhap.sh 40 > /tempdata3/linqs/Mimulus/canu/data_t8/correction/1-overlapper/mhap.000040.out 2>&1
    /tempdata3/linqs/Mimulus/canu/data_t8/correction/1-overlapper/mhap.sh 41 > /tempdata3/linqs/Mimulus/canu/data_t8/correction/1-overlapper/mhap.000041.out 2>&1
    /tempdata3/linqs/Mimulus/canu/data_t8/correction/1-overlapper/mhap.sh 42 > /tempdata3/linqs/Mimulus/canu/data_t8/correction/1-overlapper/mhap.000042.out 2>&1
    /tempdata3/linqs/Mimulus/canu/data_t8/correction/1-overlapper/mhap.sh 43 > /tempdata3/linqs/Mimulus/canu/data_t8/correction/1-overlapper/mhap.000043.out 2>&1
    /tempdata3/linqs/Mimulus/canu/data_t8/correction/1-overlapper/mhap.sh 44 > /tempdata3/linqs/Mimulus/canu/data_t8/correction/1-overlapper/mhap.000044.out 2>&1
    /tempdata3/linqs/Mimulus/canu/data_t8/correction/1-overlapper/mhap.sh 46 > /tempdata3/linqs/Mimulus/canu/data_t8/correction/1-overlapper/mhap.000046.out 2>&1
    /tempdata3/linqs/Mimulus/canu/data_t8/correction/1-overlapper/mhap.sh 47 > /tempdata3/linqs/Mimulus/canu/data_t8/correction/1-overlapper/mhap.000047.out 2>&1
    /tempdata3/linqs/Mimulus/canu/data_t8/correction/1-overlapper/mhap.sh 49 > /tempdata3/linqs/Mimulus/canu/data_t8/correction/1-overlapper/mhap.000049.out 2>&1
    /tempdata3/linqs/Mimulus/canu/data_t8/correction/1-overlapper/mhap.sh 50 > /tempdata3/linqs/Mimulus/canu/data_t8/correction/1-overlapper/mhap.000050.out 2>&1
    /tempdata3/linqs/Mimulus/canu/data_t8/correction/1-overlapper/mhap.sh 51 > /tempdata3/linqs/Mimulus/canu/data_t8/correction/1-overlapper/mhap.000051.out 2>&1
    /tempdata3/linqs/Mimulus/canu/data_t8/correction/1-overlapper/mhap.sh 52 > /tempdata3/linqs/Mimulus/canu/data_t8/correction/1-overlapper/mhap.000052.out 2>&1
    /tempdata3/linqs/Mimulus/canu/data_t8/correction/1-overlapper/mhap.sh 53 > /tempdata3/linqs/Mimulus/canu/data_t8/correction/1-overlapper/mhap.000053.out 2>&1
    /tempdata3/linqs/Mimulus/canu/data_t8/correction/1-overlapper/mhap.sh 54 > /tempdata3/linqs/Mimulus/canu/data_t8/correction/1-overlapper/mhap.000054.out 2>&1
    /tempdata3/linqs/Mimulus/canu/data_t8/correction/1-overlapper/mhap.sh 55 > /tempdata3/linqs/Mimulus/canu/data_t8/correction/1-overlapper/mhap.000055.out 2>&1
    /tempdata3/linqs/Mimulus/canu/data_t8/correction/1-overlapper/mhap.sh 56 > /tempdata3/linqs/Mimulus/canu/data_t8/correction/1-overlapper/mhap.000056.out 2>&1
    /tempdata3/linqs/Mimulus/canu/data_t8/correction/1-overlapper/mhap.sh 57 > /tempdata3/linqs/Mimulus/canu/data_t8/correction/1-overlapper/mhap.000057.out 2>&1
    /tempdata3/linqs/Mimulus/canu/data_t8/correction/1-overlapper/mhap.sh 58 > /tempdata3/linqs/Mimulus/canu/data_t8/correction/1-overlapper/mhap.000058.out 2>&1
    /tempdata3/linqs/Mimulus/canu/data_t8/correction/1-overlapper/mhap.sh 59 > /tempdata3/linqs/Mimulus/canu/data_t8/correction/1-overlapper/mhap.000059.out 2>&1
    /tempdata3/linqs/Mimulus/canu/data_t8/correction/1-overlapper/mhap.sh 60 > /tempdata3/linqs/Mimulus/canu/data_t8/correction/1-overlapper/mhap.000060.out 2>&1
    /tempdata3/linqs/Mimulus/canu/data_t8/correction/1-overlapper/mhap.sh 61 > /tempdata3/linqs/Mimulus/canu/data_t8/correction/1-overlapper/mhap.000061.out 2>&1
    /tempdata3/linqs/Mimulus/canu/data_t8/correction/1-overlapper/mhap.sh 62 > /tempdata3/linqs/Mimulus/canu/data_t8/correction/1-overlapper/mhap.000062.out 2>&1
    /tempdata3/linqs/Mimulus/canu/data_t8/correction/1-overlapper/mhap.sh 63 > /tempdata3/linqs/Mimulus/canu/data_t8/correction/1-overlapper/mhap.000063.out 2>&1
    /tempdata3/linqs/Mimulus/canu/data_t8/correction/1-overlapper/mhap.sh 65 > /tempdata3/linqs/Mimulus/canu/data_t8/correction/1-overlapper/mhap.000065.out 2>&1
    /tempdata3/linqs/Mimulus/canu/data_t8/correction/1-overlapper/mhap.sh 66 > /tempdata3/linqs/Mimulus/canu/data_t8/correction/1-overlapper/mhap.000066.out 2>&1
    /tempdata3/linqs/Mimulus/canu/data_t8/correction/1-overlapper/mhap.sh 67 > /tempdata3/linqs/Mimulus/canu/data_t8/correction/1-overlapper/mhap.000067.out 2>&1
    /tempdata3/linqs/Mimulus/canu/data_t8/correction/1-overlapper/mhap.sh 68 > /tempdata3/linqs/Mimulus/canu/data_t8/correction/1-overlapper/mhap.000068.out 2>&1

-- Finished on Tue Mar 21 20:01:16 2017 (295 seconds) with 62568.192 GB free disk space
----------------------------------------
--
-- 33 mhap jobs failed:
--   job /tempdata3/linqs/Mimulus/canu/data_t8/correction/1-overlapper/results/000032.ovb FAILED.
--   job /tempdata3/linqs/Mimulus/canu/data_t8/correction/1-overlapper/results/000033.ovb FAILED.
--   job /tempdata3/linqs/Mimulus/canu/data_t8/correction/1-overlapper/results/000034.ovb FAILED.
--   job /tempdata3/linqs/Mimulus/canu/data_t8/correction/1-overlapper/results/000036.ovb FAILED.
--   job /tempdata3/linqs/Mimulus/canu/data_t8/correction/1-overlapper/results/000037.ovb FAILED.
--   job /tempdata3/linqs/Mimulus/canu/data_t8/correction/1-overlapper/results/000038.ovb FAILED.
--   job /tempdata3/linqs/Mimulus/canu/data_t8/correction/1-overlapper/results/000039.ovb FAILED.
--   job /tempdata3/linqs/Mimulus/canu/data_t8/correction/1-overlapper/results/000040.ovb FAILED.
--   job /tempdata3/linqs/Mimulus/canu/data_t8/correction/1-overlapper/results/000041.ovb FAILED.
--   job /tempdata3/linqs/Mimulus/canu/data_t8/correction/1-overlapper/results/000042.ovb FAILED.
--   job /tempdata3/linqs/Mimulus/canu/data_t8/correction/1-overlapper/results/000043.ovb FAILED.
--   job /tempdata3/linqs/Mimulus/canu/data_t8/correction/1-overlapper/results/000044.ovb FAILED.
--   job /tempdata3/linqs/Mimulus/canu/data_t8/correction/1-overlapper/results/000046.ovb FAILED.
--   job /tempdata3/linqs/Mimulus/canu/data_t8/correction/1-overlapper/results/000047.ovb FAILED.
--   job /tempdata3/linqs/Mimulus/canu/data_t8/correction/1-overlapper/results/000049.ovb FAILED.
--   job /tempdata3/linqs/Mimulus/canu/data_t8/correction/1-overlapper/results/000050.ovb FAILED.
--   job /tempdata3/linqs/Mimulus/canu/data_t8/correction/1-overlapper/results/000051.ovb FAILED.
--   job /tempdata3/linqs/Mimulus/canu/data_t8/correction/1-overlapper/results/000052.ovb FAILED.
--   job /tempdata3/linqs/Mimulus/canu/data_t8/correction/1-overlapper/results/000053.ovb FAILED.
--   job /tempdata3/linqs/Mimulus/canu/data_t8/correction/1-overlapper/results/000054.ovb FAILED.
--   job /tempdata3/linqs/Mimulus/canu/data_t8/correction/1-overlapper/results/000055.ovb FAILED.
--   job /tempdata3/linqs/Mimulus/canu/data_t8/correction/1-overlapper/results/000056.ovb FAILED.
--   job /tempdata3/linqs/Mimulus/canu/data_t8/correction/1-overlapper/results/000057.ovb FAILED.
--   job /tempdata3/linqs/Mimulus/canu/data_t8/correction/1-overlapper/results/000058.ovb FAILED.
--   job /tempdata3/linqs/Mimulus/canu/data_t8/correction/1-overlapper/results/000059.ovb FAILED.
--   job /tempdata3/linqs/Mimulus/canu/data_t8/correction/1-overlapper/results/000060.ovb FAILED.
--   job /tempdata3/linqs/Mimulus/canu/data_t8/correction/1-overlapper/results/000061.ovb FAILED.
--   job /tempdata3/linqs/Mimulus/canu/data_t8/correction/1-overlapper/results/000062.ovb FAILED.
--   job /tempdata3/linqs/Mimulus/canu/data_t8/correction/1-overlapper/results/000063.ovb FAILED.
--   job /tempdata3/linqs/Mimulus/canu/data_t8/correction/1-overlapper/results/000065.ovb FAILED.
--   job /tempdata3/linqs/Mimulus/canu/data_t8/correction/1-overlapper/results/000066.ovb FAILED.
--   job /tempdata3/linqs/Mimulus/canu/data_t8/correction/1-overlapper/results/000067.ovb FAILED.
--   job /tempdata3/linqs/Mimulus/canu/data_t8/correction/1-overlapper/results/000068.ovb FAILED.
--
-- mhap attempt 2 begins with 40 finished, and 33 to compute.
----------------------------------------
-- Starting concurrent execution on Tue Mar 21 20:01:17 2017 with 62568.108 GB free disk space (33 processes; 1 concurrently)

    /tempdata3/linqs/Mimulus/canu/data_t8/correction/1-overlapper/mhap.sh 32 > /tempdata3/linqs/Mimulus/canu/data_t8/correction/1-overlapper/mhap.000032.out 2>&1
    /tempdata3/linqs/Mimulus/canu/data_t8/correction/1-overlapper/mhap.sh 33 > /tempdata3/linqs/Mimulus/canu/data_t8/correction/1-overlapper/mhap.000033.out 2>&1
    /tempdata3/linqs/Mimulus/canu/data_t8/correction/1-overlapper/mhap.sh 34 > /tempdata3/linqs/Mimulus/canu/data_t8/correction/1-overlapper/mhap.000034.out 2>&1
    /tempdata3/linqs/Mimulus/canu/data_t8/correction/1-overlapper/mhap.sh 36 > /tempdata3/linqs/Mimulus/canu/data_t8/correction/1-overlapper/mhap.000036.out 2>&1
    /tempdata3/linqs/Mimulus/canu/data_t8/correction/1-overlapper/mhap.sh 37 > /tempdata3/linqs/Mimulus/canu/data_t8/correction/1-overlapper/mhap.000037.out 2>&1
    /tempdata3/linqs/Mimulus/canu/data_t8/correction/1-overlapper/mhap.sh 38 > /tempdata3/linqs/Mimulus/canu/data_t8/correction/1-overlapper/mhap.000038.out 2>&1
    /tempdata3/linqs/Mimulus/canu/data_t8/correction/1-overlapper/mhap.sh 39 > /tempdata3/linqs/Mimulus/canu/data_t8/correction/1-overlapper/mhap.000039.out 2>&1
    /tempdata3/linqs/Mimulus/canu/data_t8/correction/1-overlapper/mhap.sh 40 > /tempdata3/linqs/Mimulus/canu/data_t8/correction/1-overlapper/mhap.000040.out 2>&1
    /tempdata3/linqs/Mimulus/canu/data_t8/correction/1-overlapper/mhap.sh 41 > /tempdata3/linqs/Mimulus/canu/data_t8/correction/1-overlapper/mhap.000041.out 2>&1
    /tempdata3/linqs/Mimulus/canu/data_t8/correction/1-overlapper/mhap.sh 42 > /tempdata3/linqs/Mimulus/canu/data_t8/correction/1-overlapper/mhap.000042.out 2>&1
    /tempdata3/linqs/Mimulus/canu/data_t8/correction/1-overlapper/mhap.sh 43 > /tempdata3/linqs/Mimulus/canu/data_t8/correction/1-overlapper/mhap.000043.out 2>&1
    /tempdata3/linqs/Mimulus/canu/data_t8/correction/1-overlapper/mhap.sh 44 > /tempdata3/linqs/Mimulus/canu/data_t8/correction/1-overlapper/mhap.000044.out 2>&1
    /tempdata3/linqs/Mimulus/canu/data_t8/correction/1-overlapper/mhap.sh 46 > /tempdata3/linqs/Mimulus/canu/data_t8/correction/1-overlapper/mhap.000046.out 2>&1
    /tempdata3/linqs/Mimulus/canu/data_t8/correction/1-overlapper/mhap.sh 47 > /tempdata3/linqs/Mimulus/canu/data_t8/correction/1-overlapper/mhap.000047.out 2>&1
    /tempdata3/linqs/Mimulus/canu/data_t8/correction/1-overlapper/mhap.sh 49 > /tempdata3/linqs/Mimulus/canu/data_t8/correction/1-overlapper/mhap.000049.out 2>&1
    /tempdata3/linqs/Mimulus/canu/data_t8/correction/1-overlapper/mhap.sh 50 > /tempdata3/linqs/Mimulus/canu/data_t8/correction/1-overlapper/mhap.000050.out 2>&1
    /tempdata3/linqs/Mimulus/canu/data_t8/correction/1-overlapper/mhap.sh 51 > /tempdata3/linqs/Mimulus/canu/data_t8/correction/1-overlapper/mhap.000051.out 2>&1
    /tempdata3/linqs/Mimulus/canu/data_t8/correction/1-overlapper/mhap.sh 52 > /tempdata3/linqs/Mimulus/canu/data_t8/correction/1-overlapper/mhap.000052.out 2>&1
    /tempdata3/linqs/Mimulus/canu/data_t8/correction/1-overlapper/mhap.sh 53 > /tempdata3/linqs/Mimulus/canu/data_t8/correction/1-overlapper/mhap.000053.out 2>&1
    /tempdata3/linqs/Mimulus/canu/data_t8/correction/1-overlapper/mhap.sh 54 > /tempdata3/linqs/Mimulus/canu/data_t8/correction/1-overlapper/mhap.000054.out 2>&1
    /tempdata3/linqs/Mimulus/canu/data_t8/correction/1-overlapper/mhap.sh 55 > /tempdata3/linqs/Mimulus/canu/data_t8/correction/1-overlapper/mhap.000055.out 2>&1
    /tempdata3/linqs/Mimulus/canu/data_t8/correction/1-overlapper/mhap.sh 56 > /tempdata3/linqs/Mimulus/canu/data_t8/correction/1-overlapper/mhap.000056.out 2>&1
    /tempdata3/linqs/Mimulus/canu/data_t8/correction/1-overlapper/mhap.sh 57 > /tempdata3/linqs/Mimulus/canu/data_t8/correction/1-overlapper/mhap.000057.out 2>&1
    /tempdata3/linqs/Mimulus/canu/data_t8/correction/1-overlapper/mhap.sh 58 > /tempdata3/linqs/Mimulus/canu/data_t8/correction/1-overlapper/mhap.000058.out 2>&1
    /tempdata3/linqs/Mimulus/canu/data_t8/correction/1-overlapper/mhap.sh 59 > /tempdata3/linqs/Mimulus/canu/data_t8/correction/1-overlapper/mhap.000059.out 2>&1
    /tempdata3/linqs/Mimulus/canu/data_t8/correction/1-overlapper/mhap.sh 60 > /tempdata3/linqs/Mimulus/canu/data_t8/correction/1-overlapper/mhap.000060.out 2>&1
    /tempdata3/linqs/Mimulus/canu/data_t8/correction/1-overlapper/mhap.sh 61 > /tempdata3/linqs/Mimulus/canu/data_t8/correction/1-overlapper/mhap.000061.out 2>&1
    /tempdata3/linqs/Mimulus/canu/data_t8/correction/1-overlapper/mhap.sh 62 > /tempdata3/linqs/Mimulus/canu/data_t8/correction/1-overlapper/mhap.000062.out 2>&1
    /tempdata3/linqs/Mimulus/canu/data_t8/correction/1-overlapper/mhap.sh 63 > /tempdata3/linqs/Mimulus/canu/data_t8/correction/1-overlapper/mhap.000063.out 2>&1
    /tempdata3/linqs/Mimulus/canu/data_t8/correction/1-overlapper/mhap.sh 65 > /tempdata3/linqs/Mimulus/canu/data_t8/correction/1-overlapper/mhap.000065.out 2>&1
    /tempdata3/linqs/Mimulus/canu/data_t8/correction/1-overlapper/mhap.sh 66 > /tempdata3/linqs/Mimulus/canu/data_t8/correction/1-overlapper/mhap.000066.out 2>&1
    /tempdata3/linqs/Mimulus/canu/data_t8/correction/1-overlapper/mhap.sh 67 > /tempdata3/linqs/Mimulus/canu/data_t8/correction/1-overlapper/mhap.000067.out 2>&1
    /tempdata3/linqs/Mimulus/canu/data_t8/correction/1-overlapper/mhap.sh 68 > /tempdata3/linqs/Mimulus/canu/data_t8/correction/1-overlapper/mhap.000068.out 2>&1

-- Finished on Tue Mar 21 20:05:06 2017 (229 seconds) with 62557.5 GB free disk space
----------------------------------------
--
-- 33 mhap jobs failed:
--   job /tempdata3/linqs/Mimulus/canu/data_t8/correction/1-overlapper/results/000032.ovb FAILED.
--   job /tempdata3/linqs/Mimulus/canu/data_t8/correction/1-overlapper/results/000033.ovb FAILED.
--   job /tempdata3/linqs/Mimulus/canu/data_t8/correction/1-overlapper/results/000034.ovb FAILED.
--   job /tempdata3/linqs/Mimulus/canu/data_t8/correction/1-overlapper/results/000036.ovb FAILED.
--   job /tempdata3/linqs/Mimulus/canu/data_t8/correction/1-overlapper/results/000037.ovb FAILED.
--   job /tempdata3/linqs/Mimulus/canu/data_t8/correction/1-overlapper/results/000038.ovb FAILED.
--   job /tempdata3/linqs/Mimulus/canu/data_t8/correction/1-overlapper/results/000039.ovb FAILED.
--   job /tempdata3/linqs/Mimulus/canu/data_t8/correction/1-overlapper/results/000040.ovb FAILED.
--   job /tempdata3/linqs/Mimulus/canu/data_t8/correction/1-overlapper/results/000041.ovb FAILED.
--   job /tempdata3/linqs/Mimulus/canu/data_t8/correction/1-overlapper/results/000042.ovb FAILED.
--   job /tempdata3/linqs/Mimulus/canu/data_t8/correction/1-overlapper/results/000043.ovb FAILED.
--   job /tempdata3/linqs/Mimulus/canu/data_t8/correction/1-overlapper/results/000044.ovb FAILED.
--   job /tempdata3/linqs/Mimulus/canu/data_t8/correction/1-overlapper/results/000046.ovb FAILED.
--   job /tempdata3/linqs/Mimulus/canu/data_t8/correction/1-overlapper/results/000047.ovb FAILED.
--   job /tempdata3/linqs/Mimulus/canu/data_t8/correction/1-overlapper/results/000049.ovb FAILED.
--   job /tempdata3/linqs/Mimulus/canu/data_t8/correction/1-overlapper/results/000050.ovb FAILED.
--   job /tempdata3/linqs/Mimulus/canu/data_t8/correction/1-overlapper/results/000051.ovb FAILED.
--   job /tempdata3/linqs/Mimulus/canu/data_t8/correction/1-overlapper/results/000052.ovb FAILED.
--   job /tempdata3/linqs/Mimulus/canu/data_t8/correction/1-overlapper/results/000053.ovb FAILED.
--   job /tempdata3/linqs/Mimulus/canu/data_t8/correction/1-overlapper/results/000054.ovb FAILED.
--   job /tempdata3/linqs/Mimulus/canu/data_t8/correction/1-overlapper/results/000055.ovb FAILED.
--   job /tempdata3/linqs/Mimulus/canu/data_t8/correction/1-overlapper/results/000056.ovb FAILED.
--   job /tempdata3/linqs/Mimulus/canu/data_t8/correction/1-overlapper/results/000057.ovb FAILED.
--   job /tempdata3/linqs/Mimulus/canu/data_t8/correction/1-overlapper/results/000058.ovb FAILED.
--   job /tempdata3/linqs/Mimulus/canu/data_t8/correction/1-overlapper/results/000059.ovb FAILED.
--   job /tempdata3/linqs/Mimulus/canu/data_t8/correction/1-overlapper/results/000060.ovb FAILED.
--   job /tempdata3/linqs/Mimulus/canu/data_t8/correction/1-overlapper/results/000061.ovb FAILED.
--   job /tempdata3/linqs/Mimulus/canu/data_t8/correction/1-overlapper/results/000062.ovb FAILED.
--   job /tempdata3/linqs/Mimulus/canu/data_t8/correction/1-overlapper/results/000063.ovb FAILED.
--   job /tempdata3/linqs/Mimulus/canu/data_t8/correction/1-overlapper/results/000065.ovb FAILED.
--   job /tempdata3/linqs/Mimulus/canu/data_t8/correction/1-overlapper/results/000066.ovb FAILED.
--   job /tempdata3/linqs/Mimulus/canu/data_t8/correction/1-overlapper/results/000067.ovb FAILED.
--   job /tempdata3/linqs/Mimulus/canu/data_t8/correction/1-overlapper/results/000068.ovb FAILED.
--
================================================================================
Don't panic, but a mostly harmless error occurred and canu failed.

canu failed with 'failed to compute mhap overlaps.  Made 2 attempts, jobs still failed'.

```

**Comment by qslin** [comment]
`-- Detected Java(TM) Runtime Environment '1.8.0_45' (from '/common/opt/jdk1.8.0_45/bin/java').
-- Detected gnuplot version '4.2 patchlevel 6 ' (from 'gnuplot') and image format 'png'.
-- Detected 8 CPUs and 31 gigabytes of memory.
-- Detected Sun Grid Engine in '/opt/gridengine/default'.
-- Grid engine disabled per useGrid=false option.
--
-- Allowed to run   1 job  concurrently, and use up to   8 compute threads and   31 GB memory for stage 'bogart (unitigger)'.
-- Allowed to run   1 job  concurrently, and use up to   8 compute threads and   13 GB memory for stage 'mhap (overlapper)'.
-- Allowed to run   1 job  concurrently, and use up to   8 compute threads and   13 GB memory for stage 'mhap (overlapper)'.
-- Allowed to run   1 job  concurrently, and use up to   8 compute threads and   13 GB memory for stage 'mhap (overlapper)'.
-- Allowed to run   2 jobs concurrently, and use up to   4 compute threads and    6 GB memory for stage 'read error detection (overlap error adjustment)'.
-- Allowed to run   8 jobs concurrently, and use up to   1 compute thread  and    2 GB memory for stage 'overlap error adjustment'.
-- Allowed to run   1 job  concurrently, and use up to   8 compute threads and   31 GB memory for stage 'utgcns (consensus)'.
-- Allowed to run   8 jobs concurrently, and use up to   1 compute thread  and    3 GB memory for stage 'overlap store parallel bucketizer'.
-- Allowed to run   8 jobs concurrently, and use up to   1 compute thread  and   16 GB memory for stage 'overlap store parallel sorting'.
-- Allowed to run   8 jobs concurrently, and use up to   1 compute thread  and    3 GB memory for stage 'overlapper'.
-- Allowed to run   1 job  concurrently, and use up to   8 compute threads and    8 GB memory for stage 'overlapper'.
-- Allowed to run   1 job  concurrently, and use up to   8 compute threads and    8 GB memory for stage 'overlapper'.
-- Allowed to run   1 job  concurrently, and use up to   8 compute threads and   31 GB memory for stage 'meryl (k-mer counting)'.
-- Allowed to run   2 jobs concurrently, and use up to   4 compute threads and   15 GB memory for stage 'falcon_sense (read correction)'.
-- Allowed to run   1 job  concurrently, and use up to   8 compute threads and   13 GB memory for stage 'minimap (overlapper)'.
-- Allowed to run   1 job  concurrently, and use up to   8 compute threads and   13 GB memory for stage 'minimap (overlapper)'.
-- Allowed to run   1 job  concurrently, and use up to   8 compute threads and   13 GB memory for stage 'minimap (overlapper)'.
--
-- This is canu parallel iteration #1, out of a maximum of 2 attempts.
--
-- Final error rates before starting pipeline:
--   
--   genomeSize          -- 420000000
--   errorRate           -- 0.035
--   
--   corOvlErrorRate     -- 0.105
--   obtOvlErrorRate     -- 0.105
--   utgOvlErrorRate     -- 0.105
--   
--   obtErrorRate        -- 0.105
--   
--   cnsErrorRate        -- 0.105
--
--
-- BEGIN CORRECTION
--
-- mhap attempt 1 begins with 40 finished, and 33 to compute.
----------------------------------------
-- Starting concurrent execution on Tue Mar 21 19:56:21 2017 with 62580.688 GB free disk space (33 processes; 1 concurrently)

    /tempdata3/linqs/Mimulus/canu/data_t8/correction/1-overlapper/mhap.sh 32 > /tempdata3/linqs/Mimulus/canu/data_t8/correction/1-overlapper/mhap.000032.out 2>&1
    /tempdata3/linqs/Mimulus/canu/data_t8/correction/1-overlapper/mhap.sh 33 > /tempdata3/linqs/Mimulus/canu/data_t8/correction/1-overlapper/mhap.000033.out 2>&1
    /tempdata3/linqs/Mimulus/canu/data_t8/correction/1-overlapper/mhap.sh 34 > /tempdata3/linqs/Mimulus/canu/data_t8/correction/1-overlapper/mhap.000034.out 2>&1
    /tempdata3/linqs/Mimulus/canu/data_t8/correction/1-overlapper/mhap.sh 36 > /tempdata3/linqs/Mimulus/canu/data_t8/correction/1-overlapper/mhap.000036.out 2>&1
    /tempdata3/linqs/Mimulus/canu/data_t8/correction/1-overlapper/mhap.sh 37 > /tempdata3/linqs/Mimulus/canu/data_t8/correction/1-overlapper/mhap.000037.out 2>&1
    /tempdata3/linqs/Mimulus/canu/data_t8/correction/1-overlapper/mhap.sh 38 > /tempdata3/linqs/Mimulus/canu/data_t8/correction/1-overlapper/mhap.000038.out 2>&1
    /tempdata3/linqs/Mimulus/canu/data_t8/correction/1-overlapper/mhap.sh 39 > /tempdata3/linqs/Mimulus/canu/data_t8/correction/1-overlapper/mhap.000039.out 2>&1
    /tempdata3/linqs/Mimulus/canu/data_t8/correction/1-overlapper/mhap.sh 40 > /tempdata3/linqs/Mimulus/canu/data_t8/correction/1-overlapper/mhap.000040.out 2>&1
    /tempdata3/linqs/Mimulus/canu/data_t8/correction/1-overlapper/mhap.sh 41 > /tempdata3/linqs/Mimulus/canu/data_t8/correction/1-overlapper/mhap.000041.out 2>&1
    /tempdata3/linqs/Mimulus/canu/data_t8/correction/1-overlapper/mhap.sh 42 > /tempdata3/linqs/Mimulus/canu/data_t8/correction/1-overlapper/mhap.000042.out 2>&1
    /tempdata3/linqs/Mimulus/canu/data_t8/correction/1-overlapper/mhap.sh 43 > /tempdata3/linqs/Mimulus/canu/data_t8/correction/1-overlapper/mhap.000043.out 2>&1
    /tempdata3/linqs/Mimulus/canu/data_t8/correction/1-overlapper/mhap.sh 44 > /tempdata3/linqs/Mimulus/canu/data_t8/correction/1-overlapper/mhap.000044.out 2>&1
    /tempdata3/linqs/Mimulus/canu/data_t8/correction/1-overlapper/mhap.sh 46 > /tempdata3/linqs/Mimulus/canu/data_t8/correction/1-overlapper/mhap.000046.out 2>&1
    /tempdata3/linqs/Mimulus/canu/data_t8/correction/1-overlapper/mhap.sh 47 > /tempdata3/linqs/Mimulus/canu/data_t8/correction/1-overlapper/mhap.000047.out 2>&1
    /tempdata3/linqs/Mimulus/canu/data_t8/correction/1-overlapper/mhap.sh 49 > /tempdata3/linqs/Mimulus/canu/data_t8/correction/1-overlapper/mhap.000049.out 2>&1
    /tempdata3/linqs/Mimulus/canu/data_t8/correction/1-overlapper/mhap.sh 50 > /tempdata3/linqs/Mimulus/canu/data_t8/correction/1-overlapper/mhap.000050.out 2>&1
    /tempdata3/linqs/Mimulus/canu/data_t8/correction/1-overlapper/mhap.sh 51 > /tempdata3/linqs/Mimulus/canu/data_t8/correction/1-overlapper/mhap.000051.out 2>&1
    /tempdata3/linqs/Mimulus/canu/data_t8/correction/1-overlapper/mhap.sh 52 > /tempdata3/linqs/Mimulus/canu/data_t8/correction/1-overlapper/mhap.000052.out 2>&1
    /tempdata3/linqs/Mimulus/canu/data_t8/correction/1-overlapper/mhap.sh 53 > /tempdata3/linqs/Mimulus/canu/data_t8/correction/1-overlapper/mhap.000053.out 2>&1
    /tempdata3/linqs/Mimulus/canu/data_t8/correction/1-overlapper/mhap.sh 54 > /tempdata3/linqs/Mimulus/canu/data_t8/correction/1-overlapper/mhap.000054.out 2>&1
    /tempdata3/linqs/Mimulus/canu/data_t8/correction/1-overlapper/mhap.sh 55 > /tempdata3/linqs/Mimulus/canu/data_t8/correction/1-overlapper/mhap.000055.out 2>&1
    /tempdata3/linqs/Mimulus/canu/data_t8/correction/1-overlapper/mhap.sh 56 > /tempdata3/linqs/Mimulus/canu/data_t8/correction/1-overlapper/mhap.000056.out 2>&1
    /tempdata3/linqs/Mimulus/canu/data_t8/correction/1-overlapper/mhap.sh 57 > /tempdata3/linqs/Mimulus/canu/data_t8/correction/1-overlapper/mhap.000057.out 2>&1
    /tempdata3/linqs/Mimulus/canu/data_t8/correction/1-overlapper/mhap.sh 58 > /tempdata3/linqs/Mimulus/canu/data_t8/correction/1-overlapper/mhap.000058.out 2>&1
    /tempdata3/linqs/Mimulus/canu/data_t8/correction/1-overlapper/mhap.sh 59 > /tempdata3/linqs/Mimulus/canu/data_t8/correction/1-overlapper/mhap.000059.out 2>&1
    /tempdata3/linqs/Mimulus/canu/data_t8/correction/1-overlapper/mhap.sh 60 > /tempdata3/linqs/Mimulus/canu/data_t8/correction/1-overlapper/mhap.000060.out 2>&1
    /tempdata3/linqs/Mimulus/canu/data_t8/correction/1-overlapper/mhap.sh 61 > /tempdata3/linqs/Mimulus/canu/data_t8/correction/1-overlapper/mhap.000061.out 2>&1
    /tempdata3/linqs/Mimulus/canu/data_t8/correction/1-overlapper/mhap.sh 62 > /tempdata3/linqs/Mimulus/canu/data_t8/correction/1-overlapper/mhap.000062.out 2>&1
    /tempdata3/linqs/Mimulus/canu/data_t8/correction/1-overlapper/mhap.sh 63 > /tempdata3/linqs/Mimulus/canu/data_t8/correction/1-overlapper/mhap.000063.out 2>&1
    /tempdata3/linqs/Mimulus/canu/data_t8/correction/1-overlapper/mhap.sh 65 > /tempdata3/linqs/Mimulus/canu/data_t8/correction/1-overlapper/mhap.000065.out 2>&1
    /tempdata3/linqs/Mimulus/canu/data_t8/correction/1-overlapper/mhap.sh 66 > /tempdata3/linqs/Mimulus/canu/data_t8/correction/1-overlapper/mhap.000066.out 2>&1
    /tempdata3/linqs/Mimulus/canu/data_t8/correction/1-overlapper/mhap.sh 67 > /tempdata3/linqs/Mimulus/canu/data_t8/correction/1-overlapper/mhap.000067.out 2>&1
    /tempdata3/linqs/Mimulus/canu/data_t8/correction/1-overlapper/mhap.sh 68 > /tempdata3/linqs/Mimulus/canu/data_t8/correction/1-overlapper/mhap.000068.out 2>&1

-- Finished on Tue Mar 21 20:01:16 2017 (295 seconds) with 62568.192 GB free disk space
----------------------------------------
--
-- 33 mhap jobs failed:
--   job /tempdata3/linqs/Mimulus/canu/data_t8/correction/1-overlapper/results/000032.ovb FAILED.
--   job /tempdata3/linqs/Mimulus/canu/data_t8/correction/1-overlapper/results/000033.ovb FAILED.
--   job /tempdata3/linqs/Mimulus/canu/data_t8/correction/1-overlapper/results/000034.ovb FAILED.
--   job /tempdata3/linqs/Mimulus/canu/data_t8/correction/1-overlapper/results/000036.ovb FAILED.
--   job /tempdata3/linqs/Mimulus/canu/data_t8/correction/1-overlapper/results/000037.ovb FAILED.
--   job /tempdata3/linqs/Mimulus/canu/data_t8/correction/1-overlapper/results/000038.ovb FAILED.
--   job /tempdata3/linqs/Mimulus/canu/data_t8/correction/1-overlapper/results/000039.ovb FAILED.
--   job /tempdata3/linqs/Mimulus/canu/data_t8/correction/1-overlapper/results/000040.ovb FAILED.
--   job /tempdata3/linqs/Mimulus/canu/data_t8/correction/1-overlapper/results/000041.ovb FAILED.
--   job /tempdata3/linqs/Mimulus/canu/data_t8/correction/1-overlapper/results/000042.ovb FAILED.
--   job /tempdata3/linqs/Mimulus/canu/data_t8/correction/1-overlapper/results/000043.ovb FAILED.
--   job /tempdata3/linqs/Mimulus/canu/data_t8/correction/1-overlapper/results/000044.ovb FAILED.
--   job /tempdata3/linqs/Mimulus/canu/data_t8/correction/1-overlapper/results/000046.ovb FAILED.
--   job /tempdata3/linqs/Mimulus/canu/data_t8/correction/1-overlapper/results/000047.ovb FAILED.
--   job /tempdata3/linqs/Mimulus/canu/data_t8/correction/1-overlapper/results/000049.ovb FAILED.
--   job /tempdata3/linqs/Mimulus/canu/data_t8/correction/1-overlapper/results/000050.ovb FAILED.
--   job /tempdata3/linqs/Mimulus/canu/data_t8/correction/1-overlapper/results/000051.ovb FAILED.
--   job /tempdata3/linqs/Mimulus/canu/data_t8/correction/1-overlapper/results/000052.ovb FAILED.
--   job /tempdata3/linqs/Mimulus/canu/data_t8/correction/1-overlapper/results/000053.ovb FAILED.
--   job /tempdata3/linqs/Mimulus/canu/data_t8/correction/1-overlapper/results/000054.ovb FAILED.
--   job /tempdata3/linqs/Mimulus/canu/data_t8/correction/1-overlapper/results/000055.ovb FAILED.
--   job /tempdata3/linqs/Mimulus/canu/data_t8/correction/1-overlapper/results/000056.ovb FAILED.
--   job /tempdata3/linqs/Mimulus/canu/data_t8/correction/1-overlapper/results/000057.ovb FAILED.
--   job /tempdata3/linqs/Mimulus/canu/data_t8/correction/1-overlapper/results/000058.ovb FAILED.
--   job /tempdata3/linqs/Mimulus/canu/data_t8/correction/1-overlapper/results/000059.ovb FAILED.
--   job /tempdata3/linqs/Mimulus/canu/data_t8/correction/1-overlapper/results/000060.ovb FAILED.
--   job /tempdata3/linqs/Mimulus/canu/data_t8/correction/1-overlapper/results/000061.ovb FAILED.
--   job /tempdata3/linqs/Mimulus/canu/data_t8/correction/1-overlapper/results/000062.ovb FAILED.
--   job /tempdata3/linqs/Mimulus/canu/data_t8/correction/1-overlapper/results/000063.ovb FAILED.
--   job /tempdata3/linqs/Mimulus/canu/data_t8/correction/1-overlapper/results/000065.ovb FAILED.
--   job /tempdata3/linqs/Mimulus/canu/data_t8/correction/1-overlapper/results/000066.ovb FAILED.
--   job /tempdata3/linqs/Mimulus/canu/data_t8/correction/1-overlapper/results/000067.ovb FAILED.
--   job /tempdata3/linqs/Mimulus/canu/data_t8/correction/1-overlapper/results/000068.ovb FAILED.
--
-- mhap attempt 2 begins with 40 finished, and 33 to compute.
----------------------------------------
-- Starting concurrent execution on Tue Mar 21 20:01:17 2017 with 62568.108 GB free disk space (33 processes; 1 concurrently)

    /tempdata3/linqs/Mimulus/canu/data_t8/correction/1-overlapper/mhap.sh 32 > /tempdata3/linqs/Mimulus/canu/data_t8/correction/1-overlapper/mhap.000032.out 2>&1
    /tempdata3/linqs/Mimulus/canu/data_t8/correction/1-overlapper/mhap.sh 33 > /tempdata3/linqs/Mimulus/canu/data_t8/correction/1-overlapper/mhap.000033.out 2>&1
    /tempdata3/linqs/Mimulus/canu/data_t8/correction/1-overlapper/mhap.sh 34 > /tempdata3/linqs/Mimulus/canu/data_t8/correction/1-overlapper/mhap.000034.out 2>&1
    /tempdata3/linqs/Mimulus/canu/data_t8/correction/1-overlapper/mhap.sh 36 > /tempdata3/linqs/Mimulus/canu/data_t8/correction/1-overlapper/mhap.000036.out 2>&1
    /tempdata3/linqs/Mimulus/canu/data_t8/correction/1-overlapper/mhap.sh 37 > /tempdata3/linqs/Mimulus/canu/data_t8/correction/1-overlapper/mhap.000037.out 2>&1
    /tempdata3/linqs/Mimulus/canu/data_t8/correction/1-overlapper/mhap.sh 38 > /tempdata3/linqs/Mimulus/canu/data_t8/correction/1-overlapper/mhap.000038.out 2>&1
    /tempdata3/linqs/Mimulus/canu/data_t8/correction/1-overlapper/mhap.sh 39 > /tempdata3/linqs/Mimulus/canu/data_t8/correction/1-overlapper/mhap.000039.out 2>&1
    /tempdata3/linqs/Mimulus/canu/data_t8/correction/1-overlapper/mhap.sh 40 > /tempdata3/linqs/Mimulus/canu/data_t8/correction/1-overlapper/mhap.000040.out 2>&1
    /tempdata3/linqs/Mimulus/canu/data_t8/correction/1-overlapper/mhap.sh 41 > /tempdata3/linqs/Mimulus/canu/data_t8/correction/1-overlapper/mhap.000041.out 2>&1
    /tempdata3/linqs/Mimulus/canu/data_t8/correction/1-overlapper/mhap.sh 42 > /tempdata3/linqs/Mimulus/canu/data_t8/correction/1-overlapper/mhap.000042.out 2>&1
    /tempdata3/linqs/Mimulus/canu/data_t8/correction/1-overlapper/mhap.sh 43 > /tempdata3/linqs/Mimulus/canu/data_t8/correction/1-overlapper/mhap.000043.out 2>&1
    /tempdata3/linqs/Mimulus/canu/data_t8/correction/1-overlapper/mhap.sh 44 > /tempdata3/linqs/Mimulus/canu/data_t8/correction/1-overlapper/mhap.000044.out 2>&1
    /tempdata3/linqs/Mimulus/canu/data_t8/correction/1-overlapper/mhap.sh 46 > /tempdata3/linqs/Mimulus/canu/data_t8/correction/1-overlapper/mhap.000046.out 2>&1
    /tempdata3/linqs/Mimulus/canu/data_t8/correction/1-overlapper/mhap.sh 47 > /tempdata3/linqs/Mimulus/canu/data_t8/correction/1-overlapper/mhap.000047.out 2>&1
    /tempdata3/linqs/Mimulus/canu/data_t8/correction/1-overlapper/mhap.sh 49 > /tempdata3/linqs/Mimulus/canu/data_t8/correction/1-overlapper/mhap.000049.out 2>&1
    /tempdata3/linqs/Mimulus/canu/data_t8/correction/1-overlapper/mhap.sh 50 > /tempdata3/linqs/Mimulus/canu/data_t8/correction/1-overlapper/mhap.000050.out 2>&1
    /tempdata3/linqs/Mimulus/canu/data_t8/correction/1-overlapper/mhap.sh 51 > /tempdata3/linqs/Mimulus/canu/data_t8/correction/1-overlapper/mhap.000051.out 2>&1
    /tempdata3/linqs/Mimulus/canu/data_t8/correction/1-overlapper/mhap.sh 52 > /tempdata3/linqs/Mimulus/canu/data_t8/correction/1-overlapper/mhap.000052.out 2>&1
    /tempdata3/linqs/Mimulus/canu/data_t8/correction/1-overlapper/mhap.sh 53 > /tempdata3/linqs/Mimulus/canu/data_t8/correction/1-overlapper/mhap.000053.out 2>&1
    /tempdata3/linqs/Mimulus/canu/data_t8/correction/1-overlapper/mhap.sh 54 > /tempdata3/linqs/Mimulus/canu/data_t8/correction/1-overlapper/mhap.000054.out 2>&1
    /tempdata3/linqs/Mimulus/canu/data_t8/correction/1-overlapper/mhap.sh 55 > /tempdata3/linqs/Mimulus/canu/data_t8/correction/1-overlapper/mhap.000055.out 2>&1
    /tempdata3/linqs/Mimulus/canu/data_t8/correction/1-overlapper/mhap.sh 56 > /tempdata3/linqs/Mimulus/canu/data_t8/correction/1-overlapper/mhap.000056.out 2>&1
    /tempdata3/linqs/Mimulus/canu/data_t8/correction/1-overlapper/mhap.sh 57 > /tempdata3/linqs/Mimulus/canu/data_t8/correction/1-overlapper/mhap.000057.out 2>&1
    /tempdata3/linqs/Mimulus/canu/data_t8/correction/1-overlapper/mhap.sh 58 > /tempdata3/linqs/Mimulus/canu/data_t8/correction/1-overlapper/mhap.000058.out 2>&1
    /tempdata3/linqs/Mimulus/canu/data_t8/correction/1-overlapper/mhap.sh 59 > /tempdata3/linqs/Mimulus/canu/data_t8/correction/1-overlapper/mhap.000059.out 2>&1
    /tempdata3/linqs/Mimulus/canu/data_t8/correction/1-overlapper/mhap.sh 60 > /tempdata3/linqs/Mimulus/canu/data_t8/correction/1-overlapper/mhap.000060.out 2>&1
    /tempdata3/linqs/Mimulus/canu/data_t8/correction/1-overlapper/mhap.sh 61 > /tempdata3/linqs/Mimulus/canu/data_t8/correction/1-overlapper/mhap.000061.out 2>&1
    /tempdata3/linqs/Mimulus/canu/data_t8/correction/1-overlapper/mhap.sh 62 > /tempdata3/linqs/Mimulus/canu/data_t8/correction/1-overlapper/mhap.000062.out 2>&1
    /tempdata3/linqs/Mimulus/canu/data_t8/correction/1-overlapper/mhap.sh 63 > /tempdata3/linqs/Mimulus/canu/data_t8/correction/1-overlapper/mhap.000063.out 2>&1
    /tempdata3/linqs/Mimulus/canu/data_t8/correction/1-overlapper/mhap.sh 65 > /tempdata3/linqs/Mimulus/canu/data_t8/correction/1-overlapper/mhap.000065.out 2>&1
    /tempdata3/linqs/Mimulus/canu/data_t8/correction/1-overlapper/mhap.sh 66 > /tempdata3/linqs/Mimulus/canu/data_t8/correction/1-overlapper/mhap.000066.out 2>&1
    /tempdata3/linqs/Mimulus/canu/data_t8/correction/1-overlapper/mhap.sh 67 > /tempdata3/linqs/Mimulus/canu/data_t8/correction/1-overlapper/mhap.000067.out 2>&1
    /tempdata3/linqs/Mimulus/canu/data_t8/correction/1-overlapper/mhap.sh 68 > /tempdata3/linqs/Mimulus/canu/data_t8/correction/1-overlapper/mhap.000068.out 2>&1

-- Finished on Tue Mar 21 20:05:06 2017 (229 seconds) with 62557.5 GB free disk space
----------------------------------------
--
-- 33 mhap jobs failed:
--   job /tempdata3/linqs/Mimulus/canu/data_t8/correction/1-overlapper/results/000032.ovb FAILED.
--   job /tempdata3/linqs/Mimulus/canu/data_t8/correction/1-overlapper/results/000033.ovb FAILED.
--   job /tempdata3/linqs/Mimulus/canu/data_t8/correction/1-overlapper/results/000034.ovb FAILED.
--   job /tempdata3/linqs/Mimulus/canu/data_t8/correction/1-overlapper/results/000036.ovb FAILED.
--   job /tempdata3/linqs/Mimulus/canu/data_t8/correction/1-overlapper/results/000037.ovb FAILED.
--   job /tempdata3/linqs/Mimulus/canu/data_t8/correction/1-overlapper/results/000038.ovb FAILED.
--   job /tempdata3/linqs/Mimulus/canu/data_t8/correction/1-overlapper/results/000039.ovb FAILED.
--   job /tempdata3/linqs/Mimulus/canu/data_t8/correction/1-overlapper/results/000040.ovb FAILED.
--   job /tempdata3/linqs/Mimulus/canu/data_t8/correction/1-overlapper/results/000041.ovb FAILED.
--   job /tempdata3/linqs/Mimulus/canu/data_t8/correction/1-overlapper/results/000042.ovb FAILED.
--   job /tempdata3/linqs/Mimulus/canu/data_t8/correction/1-overlapper/results/000043.ovb FAILED.
--   job /tempdata3/linqs/Mimulus/canu/data_t8/correction/1-overlapper/results/000044.ovb FAILED.
--   job /tempdata3/linqs/Mimulus/canu/data_t8/correction/1-overlapper/results/000046.ovb FAILED.
--   job /tempdata3/linqs/Mimulus/canu/data_t8/correction/1-overlapper/results/000047.ovb FAILED.
--   job /tempdata3/linqs/Mimulus/canu/data_t8/correction/1-overlapper/results/000049.ovb FAILED.
--   job /tempdata3/linqs/Mimulus/canu/data_t8/correction/1-overlapper/results/000050.ovb FAILED.
--   job /tempdata3/linqs/Mimulus/canu/data_t8/correction/1-overlapper/results/000051.ovb FAILED.
--   job /tempdata3/linqs/Mimulus/canu/data_t8/correction/1-overlapper/results/000052.ovb FAILED.
--   job /tempdata3/linqs/Mimulus/canu/data_t8/correction/1-overlapper/results/000053.ovb FAILED.
--   job /tempdata3/linqs/Mimulus/canu/data_t8/correction/1-overlapper/results/000054.ovb FAILED.
--   job /tempdata3/linqs/Mimulus/canu/data_t8/correction/1-overlapper/results/000055.ovb FAILED.
--   job /tempdata3/linqs/Mimulus/canu/data_t8/correction/1-overlapper/results/000056.ovb FAILED.
--   job /tempdata3/linqs/Mimulus/canu/data_t8/correction/1-overlapper/results/000057.ovb FAILED.
--   job /tempdata3/linqs/Mimulus/canu/data_t8/correction/1-overlapper/results/000058.ovb FAILED.
--   job /tempdata3/linqs/Mimulus/canu/data_t8/correction/1-overlapper/results/000059.ovb FAILED.
--   job /tempdata3/linqs/Mimulus/canu/data_t8/correction/1-overlapper/results/000060.ovb FAILED.
--   job /tempdata3/linqs/Mimulus/canu/data_t8/correction/1-overlapper/results/000061.ovb FAILED.
--   job /tempdata3/linqs/Mimulus/canu/data_t8/correction/1-overlapper/results/000062.ovb FAILED.
--   job /tempdata3/linqs/Mimulus/canu/data_t8/correction/1-overlapper/results/000063.ovb FAILED.
--   job /tempdata3/linqs/Mimulus/canu/data_t8/correction/1-overlapper/results/000065.ovb FAILED.
--   job /tempdata3/linqs/Mimulus/canu/data_t8/correction/1-overlapper/results/000066.ovb FAILED.
--   job /tempdata3/linqs/Mimulus/canu/data_t8/correction/1-overlapper/results/000067.ovb FAILED.
--   job /tempdata3/linqs/Mimulus/canu/data_t8/correction/1-overlapper/results/000068.ovb FAILED.
--
================================================================================
Don't panic, but a mostly harmless error occurred and canu failed.

canu failed with 'failed to compute mhap overlaps.  Made 2 attempts, jobs still failed'.

`

**Comment by qslin** [comment]
[canufailed.txt](https://github.com/marbl/canu/files/860197/canufailed.txt)

**Comment by skoren** [comment]
Are these jobs being run one at a time (the should be based on available cores/memory)? I want to confirm it's not launching all mhap.sh jobs simultaneously. What's the output from one of the failed jobs (like ```correction/1-overlapper/mhap.*33.out```).

**Comment by qslin** [comment]
Here is the output file mhap.000033.out
```
Running job 33 based on command line options.
Running block 000009 in query 000033
mhapConvert: mhap/mhapConvert.C:120: int main(int, char**): Assertion `W[4][0] == '0'' failed.
/tempdata3/linqs/Mimulus/canu/data_t8/correction/1-overlapper/mhap.sh: line 600:  7284 Aborted                 (core dumped) $bin/mhapConvert $cvt -o /tempdata3/linqs/Mimulus/canu/data_t8/correction/1-overlapper/results/$qry.mhap.ovb.WORKING /tempdata3/linqs/Mimulus/canu/data_t8/correction/1-overlapper/results/$qry.mhap
```

**Comment by qslin** [comment]
How to check if the jobs were run one at a time or not? Thank you!

**Comment by skoren** [comment]
The logs say it is running 1 at a time so as long as it prints one command, waits a bit, then prints the next one, and so on, they are running correctly.

The error indicates the intermediate output from a previous run is corrupted. Can you try removing correction/1-overlapper/results/*.mhap and re-starting Canu to see if it will continue this time. If not, you may have had corruption in the precompute.sh step (Canu 1.4 had a bug that could not detect a failure in this step which was fixed a few months ago) it which case it would be best to update to the latest code from git and re-start the assembly from scratch.

**Comment by qslin** [comment]
Yes, it succeeded after I removed the previous outputs. Thank you!

**Comment by chenshixuan** [comment]
I have the same problem like yous ,what previous outputs  did you remove?  I removerd  the mhap.sh previous output ,but the error log still exists,   howerver ,  my  10 mhap precompute jobs finished successfully.  Thank you!

**Comment by chenshixuan** [comment]
I have the same problem like yous ,what previous outputs did you remove? I removerd the mhap.sh previous output ,but the error log still exists, howerver , my 10 mhap precompute jobs finished successfully. Thank you! （非常感谢）

**Comment by skoren** [comment]
Please don't comment on closed issues, it makes it hard to track which user/error is requesting help and the issue is likely referring to an old version of Canu that it's relevant anymore. In this issue, there was a bug in Canu 1.4 (fixed in the 1.5 release) that precompute failed but didn't report the error so if you are running 1.5 this is the same as your error. Removing the output of precompute (```blocks/*```) fixed the issue. Have you checked the output from the mhap run (```mhap.*.out```) for the error message and the outputs of ```precompute.*.out```?

**Comment by chenshixuan** [comment]
yet my mhap.*.out ,"Total matches found: 1411665
Average number of matches per lookup: 74.07981738035265
Average number of table elements processed per lookup: 13359.783165407222
Average number of table elements processed per match: 180.34308989739068
Average % of hashed sequences hit per lookup: 2.1288828572597174
Average % of hashed sequences hit that are matches: 26.65250274848359
Average % of hashed sequences fully compared that are matches: 88.78111456802328
mhapConvert: mhap/mhapConvert.C:120: int main(int, char**): Assertion `W[4][0] == '0'' failed.
/opt/gridengine/default/spool/supermem-11-1/job_scripts/7225593: line 22: 62887 Aborted                 (core dumped)"


I have removed the output of precompute (blocks/*) as your guidence ,restart the job ,still failed . correction/*.ovlStore.err  ：Failed with 'Segmentation fault'.  the work errorlog is 
"-- Starting command on Thu Apr 20 15:06:54 2017 with 852.895 GB free disk space
/XXXXXXX/canu/canu-1.4/Linux-amd64/bin/ovStoreBuild \
 -O  /XXXXXXX/correction/Arabidopsis.gkpStore \
     -M 2-8 \
     -L /XXXXXXX/correction/1-overlapper/ovljob.files \
     > /XXXXXXX/correction/Arabidopsis.ovlStore.err 2>&1
-- Finished on Thu Apr 20 15:06:57 2017 (3 seconds) with 852.885 GB free disk space
----------------------------------------
ERROR:
ERROR:  Failed with exit code 1.  (rc=256)
ERROR:
================================================================================
Don't panic, but a mostly harmless error occurred and canu failed.

Disk space available:  852.885 GB

Last 50 lines of the relevant log file (/XXXXXXX/correction/Arabidopsis.ovlStore.err):


canu failed with 'failed to create the overlap store'.

**Comment by brianwalenz** [comment]
The `correction/Arabidopsis.ovlStore.err` file is empty?  What is in it?

Can you run the `ovStoreBuild` command by hand, without the redirection?  That is, run:
```
/XXXXXXX/canu/canu-1.4/Linux-amd64/bin/ovStoreBuild \
 -O  /XXXXXXX/correction/Arabidopsis.gkpStore \
     -M 2-8 \
     -L /XXXXXXX/correction/1-overlapper/ovljob.files
```

You're not too far into the assembly process, and I'd strongly recommend restarting from scratch using the just-released 1.5 version instead of 1.4.

**Comment by chenshixuan** [comment]
thank you  very much !!!    I used  1.5 version to run the job, and it succeeded !

**Comment by brianwalenz** [comment]
Awesome, glad to hear!
